baseURL = "https://remigioamc.github.io/"
languageCode = "en-us"
title = "Gones"
theme = "hugo-initio"
publishDir = "docs"

[params]
    name = "Gones Tax & Consulting"
    description = "Tax & Consulting"
    nombre1 = "José Antonio González"
    email1 = "josea.gonzalez@gonestax.com"
    phone1 = "55-7268-2638"
    nombre2 = "Guillermo Esquivel"
    email2 = "josea.gonzalez@gonestax.com"
    phone2 = "55-1624- 2495"
    nombre3 = "Salvador López"
    email3 = "josea.gonzalez@gonestax.com"
    phone3 = "7095-1152"
    address = "AVENIDA REVOLUCION No. 1125 INT 7 COL MERCED GOMEZ.C.P. 03930 BENITO JUAREZ, CDMX, MEXICO."
    year = 2017
    background = ""
    favicon = "images/gt_favicon.png"
    DateForm = "January 2, 2006"

    showSubheader = true
    showServices = true
    showRecentWorks = false
    showDownload = true
    showClients = true
    showVision = true
    showMision = true
    showSomos = true
    

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Misión"
    url = "/#mision"
    weight = 2
[[menu.main]]
    name = "Visión"
    url = "/#vision"
    weight = 3
[[menu.main]]
    name = "¿Quiénes somos?"
    url = "/#somos"
    weight = 4
[[menu.main]]
    name = "Servicios"
    url = "/#services"
    weight = 5

[params.disqus]
    site = "hugo-initio-site.disqus.com"

[params.sharethis]
    property = "123456789012345678901234"
    custom = true

[params.google.analytics]
    trackerID = "GA-000000000-0"

[[params.social]]
	title = "facebook"
	url = "https://www.facebook.com/nickname"
    icon = "fa-facebook-square"
    footer = true
    sharethis = true
    network = "facebook"
[[params.social]]
	title = "twitter"
	url = "https://twitter.com/nickname"
    icon = "fa-twitter-square"
    footer = true
    sharethis = true
    network = "twitter"
[[params.social]]
	title = "instagram"
	url = "https://www.instagram.com/nickname"
    icon = "fa-instagram"
    footer = false
    sharethis = false
    network = ""
[[params.social]]
	title = "google+"
	url = "https://plus.google.com/+nickname"
    icon = "fa-google-plus-square"
    footer = false
    sharethis = false
    network = "googleplus"
[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/nickname"
    icon = "fa-linkedin-square"
    footer = false
    sharethis = false
    network = "linkedin"
[[params.social]]
	title = "tumblr"
	url = "https://nickname.tumblr.com"
    icon = "fa-tumblr-square"
    footer = false
    sharethis = false
    network = "tumblr"
[[params.social]]
	title = "github"
	url = "https://github.com/nickname"
    icon = "fa-github"
    footer = false
    sharethis = false
    network = ""
[[params.social]]
	title = "email"
	url = "mailto:some.email@somewhere.com"
    icon = "fa-envelope"
    footer = true
    sharethis = true
    network = "email"
